Section "ServerFlags"
    Option "AutoAddGPU" "off"
    Option "AutoEnableDevices" "off"
EndSection

Section "Device"
    Identifier "TFT"
    Driver "fbdev"
    Option "fbdev" "/dev/fb0"
EndSection

Section "Monitor"
    Identifier "TFTMonitor"
EndSection

Section "Screen"
    Identifier "TFTScreen"
    Device "TFT"
    Monitor "TFTMonitor"
EndSection

Section "ServerLayout"
    Identifier "TFTLayout"
    Screen "TFTScreen"
EndSection
